data:
  api_url: "https://www.postdata.gov.co/api/action/datastore/search.json?resource_id=d40c5e75-db56-4ec1-a441-0314c47bd71d&limit=1100"
  target: "trafico"
  dropna_target: true
  dropna_all: false

model:
  test_size: 0.2
  random_state: 42
  n_estimators: 100

mlflow:
  tracking_uri: "file:./mlruns"
  experiment_name: "trafico-internet-movil"